CREATE OR REPLACE FILE FORMAT WEATHER_JSON_FORMAT
TYPE = JSON;

CREATE OR REPLACE TABLE WEATHER_RAW (
    RAW_DATA VARIANT
);

CREATE OR REPLACE STAGE WEATHER_S3_STAGE
URL = 's3://weather-json-data-yourname/weather-data/'
CREDENTIALS = (
  AWS_KEY_ID = 'YOUR_ACCESS_KEY'
  AWS_SECRET_KEY = 'YOUR_SECRET_KEY'
)
FILE_FORMAT = WEATHER_JSON_FORMAT;